image:https://github.com/livk-cloud/spring-boot-example/actions/workflows/gradle.yml/badge.svg?branch=main["Build Status",
link="https://github.com/livk-cloud/spring-boot-example/actions/workflows/gradle.yml"]

== Spring Boot Example

link:README-en.adoc[English] | link:README.adoc[简体中文] +
image:https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white["Build Status",link="https://github.com/livk-cloud/spring-boot-example"] +
image:https://img.shields.io/badge/Gitee-C71D23?style=for-the-badge&logo=gitee&logoColor=white["Build Status",link="https://gitee.com/livk-cloud/spring-boot-example"] +
https://github.com/livk-cloud/spring-cloud-example[The official version of the Move `Spring Cloud` project] +

Here is a various example on springboot project +
Use 3rd party packages to basically overwrite the latest version +
Various ways of using Gradle and examples +
Also includes a variety of custom Spring Boot Starter +
The code inside should more or less help you +
If you feel good, you can star it +
Mock and WebclientTest tests cover most functions +
JDK:17(latest LTS) +
SpringBoot: 3.0.0(latest GA version) +
Gradle: 7.6(current the latest version) +

link:gradle.properties[Project information] +
link:gradle/libs.versions.toml[version control] +
link:example.adoc[example details] +
link:upgrade-log.adoc[upgrade documentation] +

Profiling using the https://github.com/gradle/gradle-profiler[Gradle-Profiler] profiler

[source,shell,indent=0]
----
gradle-profiler --gradle-user-home D:\gradle-7.6 --benchmark --cli --project-dir ./ clean
----

image:https://img.shields.io/badge/mysql-%2300f.svg?style=for-the-badge&logo=mysql&logoColor=white[link="https://www.mysql.com/"]
image:https://img.shields.io/badge/postgres-%23316192.svg?style=for-the-badge&logo=postgresql&logoColor=white[link="https://www.postgresql.org/"]
image:https://img.shields.io/badge/Apache%20Kafka-000?style=for-the-badge&logo=apachekafka[link="https://kafka.apache.org/"]
image:https://img.shields.io/badge/Rabbitmq-FF6600?style=for-the-badge&logo=rabbitmq&logoColor=white[link="https://www.rabbitmq.com/"]
image:https://img.shields.io/badge/redis-%23DD0031.svg?style=for-the-badge&logo=redis&logoColor=white[link="https://redis.io/"]
image:https://pulsar.apache.org/img/logo.svg[width=140 height=140,link="https://pulsar.apache.org/"]
image:https://clickhouse.com/docs/img/logo_without_text.svg[link="https://clickhouse.com/"]
