= Spring Boot Example

link:README-en.adoc[English]|link:README.adoc[简体中文] +
https://github.com/livk-cloud/spring-boot-example[GitHub] | https://gitee.com/livk-cloud/spring-boot-example[Gitee] +
https://github.com/livk-cloud/spring-cloud-example[正式版移步 `Spring Cloud` 项目] +

这是一个关于springboot项目的各种示例 +
使用第三方包基本覆盖最新版本 +
关于Gradle的各种使用方式以及示例 +
同时包含了各种自定义Spring Boot Starter +
里面的代码或多或少应该可以帮助到你 +
如果觉得不错，可以star一下 +
Mock与WebclientTest测试覆盖大部分功能 +
JDK:17(最新LTS) +
SpringBoot: 3.0.0(最新正式版) +
Gradle: 7.5.1(当前最新版) +

link:gradle.properties[项目信息] +
link:gradle/libs.versions.toml[版本控制] +
link:example.adoc[示例详情] +
link:upgrade-log.adoc[升级文档] +

使用 https://github.com/gradle/gradle-profiler[Gradle-Profiler]分析器进行分析

[source,shell,indent=0]
----
gradle-profiler --gradle-user-home D:\gradle-7.5.1 --benchmark --cli --project-dir ./ clean
----

https://qm.qq.com/cgi-bin/qm/qr?k=7mqPb8JcXoDpFkk4Vx7CcFFrIXrIxbVE&jump_from=webapi&authKey=twOCFhCWeYIiP4DNWM91BjGcPXuxpWikyk2Dh+fFctht5xcvT9N8PUsVMUcKQvJf"[QQ群 857146133]

#中间件#：MySql、Postgres、ClickHouse、Kafka、Pulsar、Rabbit、Redis、Zookeeper +

#框架#：
[%autowidth]

|===
|名称 |功能

|Spring-Boot-Admin
|springboot监控服务

|Spring-Authorization-Server
|spring授权服务器

|Spring-Batch
|spring批次处理框架

|Springdoc-Openapi
|新版Swagger API文档

|EasyExcel
|便捷的Excel处理框架

|GraphQL
|查询语言规划

|Spring-Hateoas
|restful风格处理框架

|Ip2region
|ip地址查询框架

|Mapstruct
|优秀的实体转换工具

|Mybatis
|半自动ORM框架

|Google Zxing Javase
|谷歌二维码生成框架

|Quartz
|定时任务框架

|R2dbc-postgresql
|异步数据库协议

|Spring-Restdocs
|API文档生成框架

|Spring-Retry
|重试框架

|Spring-Security
|安全框架

|Browscap-Java、Yauaa
|HTTP用户信息解析框架
|===

