GET http://localhost:9977/user
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpZCI6IjEzZWQ1YTUzLTQ5ZjctNGE5OS1hODk1LTkyMTE1YmI1YzY0ZiIsInVzZXJJbmZvIjp7InVzZXJuYW1lIjoibGl2ayIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dfX0.mkf61viahOc1pZZMFkCgC7_VIhmgI0wZBOVawXhg5d5oKbRzDrUticSE_lDfRTx11a_0Fz4IgfbgWokwr3on9L4U2pvafuSdccscFncc4Xrt8q9Fm_lGrbthpi337bIZFgnIo2iYG5FhwbIol6B0vIEpHO3-hXmhiV4Kgxz4EX0rykehy51KMl7CxQ1ffQlD2z-P6QVvt2MqX666ifaKFbX6IzdvMXmpPpPpai9q7GinCsuBxy0lEXVDwz3dfuKPNNw4E1RrZ9q1shFiPtG9jXVctrvC9vIGbP9OI3xReaytLn8I3-8DNqb_n3544f6y2KlGzwG_j5k57ABBh_rUUw
